package com.example.urlshortener.common.error;

public enum ErrorCode {
    VALIDATION_FAILED,
    RESERVED_CUSTOM_ALIAS,
    CUSTOM_ALIAS_ALREADY_EXISTS,
    SHORT_URL_NOT_FOUND,
    SHORT_CODE_ALLOCATION_FAILED,
    DEPENDENCY_UNAVAILABLE,
    INTERNAL_ERROR
}
