CREATE TABLE url_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code VARCHAR(32) NOT NULL,
    original_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at TIMESTAMPTZ NULL,
    click_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_url_mapping_short_code UNIQUE (short_code),
    CONSTRAINT ck_url_mapping_short_code_length
        CHECK (char_length(short_code) BETWEEN 3 AND 32),
    CONSTRAINT ck_url_mapping_short_code_characters
        CHECK (short_code ~ '^[A-Za-z0-9][A-Za-z0-9-]*[A-Za-z0-9]$'),
    CONSTRAINT ck_url_mapping_click_count_non_negative
        CHECK (click_count >= 0)
);
